### ISSUE TITLE
Add a Previous Team section in the official website

### ISSUE THREAD

**Issue by aniruddha2000** [Radiumskull/dscbppimt-official-website#11]
# Add a Previous Team section in the official website
Add an area/button such as a alumni where people can go and see the previous members & cores and their respective information with their year.
Example - [https://www.dscjss.in/alumni](https://www.dscjss.in/alumni)
### Approach
Also need to add a [teamHelper.js](https://github.com/Radiumskull/dscbppimt-official-website/blob/master/components/helper/teamHelper.js) and a [alumni.js](https://github.com/Radiumskull/dscbppimt-official-website/blob/master/pages/team.js) where we will add the previous team member there. So @Radiumskull can you add the information about where we need to call those in the project.

**Comment by ArkaprabhaChakraborty** [comment]
I need to know about the navigation bar code and the "routing" code.

**Comment by Radiumskull** [comment]
@ArkaprabhaChakraborty In NextJS, if you want to add new pages, add files in the 'pages' folder. The name of the file will be treated as the route to that page. For example, if you want to add '/alumni' add alumni.js in the pages folder.

For navigating between pages, next provides 'Link' component. You can refer to the existing '/components/navbar.js'

**Comment by ArkaprabhaChakraborty** [comment]
Okay which one is deployed? This repo or the repo in dscbppimt organistaion? I think that is the one deployed?

**Comment by ArkaprabhaChakraborty** [comment]
Okay I figured it out :) And there is a PR
